# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobuf/user/user.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class User(betterproto.Message):
    id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    password: str = betterproto.string_field(3)
