# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobuf/tasks/tasks.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Task(betterproto.Message):
    id: str = betterproto.string_field(1)
    task: str = betterproto.string_field(2)
    user_id: str = betterproto.string_field(3)


@dataclass
class User(betterproto.Message):
    id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    tasks: List["Task"] = betterproto.message_field(3)
