DATABASE_PATH = 'tasks.db'

USER_TABLE_NAME = 'users'
TASK_TABLE_NAME = 'task'

USER_NAME = 'user_name'
PASSWORD = 'password'

TASK = 'task'
USER = 'user'


CREATE_USER_TABLE = f'''
    CREATE TABLE IF NOT EXISTS {USER_TABLE_NAME} (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        {USER_NAME} TEXT NOT NULL,
        {PASSWORD} TEXT NOT NULL
    )
'''

CREATE_TASK_TABLE = f'''
    CREATE TABLE IF NOT EXISTS {TASK_TABLE_NAME} (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        {TASK} TEXT NOT NULL,
        {USER} INTEGER NOT NULL,
        FOREIGN KEY ({USER}) REFERENCES {USER_TABLE_NAME}(id)
    )
        '''