# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ticket.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class MedicamentoType(betterproto.Enum):
    NONE = 0
    AMPOLA = 1
    PACOTE = 2


@dataclass
class Medicamento(betterproto.Message):
    name: str = betterproto.string_field(1)
    quantidade: int = betterproto.int32_field(2)
    tipo: "MedicamentoType" = betterproto.enum_field(3)


@dataclass
class Ticket(betterproto.Message):
    medicamentos: List["Medicamento"] = betterproto.message_field(1)
